apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mlflow-tracking-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mlflow-tracking
    spec:
      containers:
      - name: mlflow-tracking-container
        image: mrnivram/mlflow:latest
        ports:
        - containerPort: 5000
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: storage-secret
              key: azurestorageconnectionstring
        - name: MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT
          valueFrom:
            secretKeyRef:
              name: storage-secret
              key: azurestorageaccountartifact
        - name: MLFLOW_SERVER_FILE_STORE
          value: "/mnt/azure/mlruns"
        - name: MLFLOW_SERVER_HOST
          value: "0.0.0.0"
        - name: MLFLOW_SERVER_PORT
          value: "5000"
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: mlflow-tracking
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mlflow-tracking-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: mlflow.localhost
    http:
      paths:
      - path: /mlflow
        backend:
          serviceName: mlflow-tracking-service
          servicePort: http
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:azure-cloud-provider
rules:
- apiGroups: ['']
  resources: ['secrets']
  verbs:     ['get','create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:azure-cloud-provider
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-cloud-provider
subjects:
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi